### ISSUE TITLE
warning: remote HEAD refers to nonexistent ref, unable to checkout.

### ISSUE THREAD

**Issue by 0mid** [Hightor/gitinfo2#4]
I just tried to clone the gitinfo2 repo, but received the following "warning:"

```
warning: remote HEAD refers to nonexistent ref, unable to checkout.
```

I put "warning" in quotes, because to me this look more like an error: One cannot checkout unless one chooses to checkout a commit other than what the remote HEAD refers to.

**Comment by longborough** [comment]
(Disclaimer: I'm working at the limits of my git capacity)

I think this may be due to the repository having no `master` branch, only `CTAN` (in place of master) and `develop`.

I suggest that, after cloning, you try `git checkout CTAN`, `git checkout develop`, or both. 

Alternatively, `git checkout -b master origin/CTAN`

**Comment by longborough** [comment]
As there's no feedback, I'm closing this "for tidiness". Please feel free to reopen if you still have problems.
